### ISSUE TITLE
Completion doesn't work

### ISSUE THREAD

**Issue by ddovod** [sebastiw/distel-completion#6]
Hello.
I have some issue with company-distel.
All I do is:
- Create new file
- Open it
- Try to complete something from lists module like lists:|

And in *Messages* buffer I see some strange errors (also without company-yasnippet):
```
Company: An error occurred in auto-begin
Company: backend (company-distel :with company-yasnippet) error "Args out of range: 1, 21" with args (candidates lists:)
Scanning for dabbrevs...done
Event: data
data: w
arg: w
nodedown: emacs@space-rocket
error in process filter: epmd-recv-port-resp: Assertion failed: (> (length arg) 2)
error in process filter: Assertion failed: (> (length arg) 2)
```
Note that after "data: w" and "arg: w" there's some symbol (^A), just for info.
I have latest distel from master branch, latest company-distel, emacs 24.5.1 on the Ubuntu 14.10 and following distel config:
```
(add-to-list 'load-path "~/.emacs.d/distel/elisp")
(require 'distel)
(distel-setup)

(defvar inferior-erlang-prompt-timeout t)
(setq inferior-erlang-machine-options '("-sname" "emacs"))
(setq erl-nodename-cache
      (make-symbol
       (concat
        "emacs@"
        (car (split-string (shell-command-to-string "hostname"))))))

(add-to-list 'load-path "~/.emacs.d/company-distel")
(require 'company-distel)
(require 'company)
(add-to-list 'company-backends '(company-distel :with company-yasnippet))
```

Maybe I'm doing something wrong?
Thank you a lot!

**Comment by sebastiw** [comment]
Hi @ddovod,

This looks like a distel problem. Does pingning distel works? `C-d g` or `M-x erl-ping` I think.
What is the reply? is it also `Assertion failed`?

**Comment by sebastiw** [comment]
Closed issue due to no reply
