### ISSUE TITLE
Melpa?

### ISSUE THREAD

**Issue by mriehl** [sebastiw/distel-completion#9]
Hi,

Would you consider making `company-distel` a package on [melpa.org](https://melpa.org/)?
Having to clone repositories into `.emacs.d` is really cumbersome especially in order to get updates or when setting up a new box.

**Comment by sebastiw** [comment]
You shall ask and recieve https://github.com/melpa/melpa/pull/4130  =)

**Comment by sebastiw** [comment]
and now it was merged melpa/melpa#4146 :)

**Comment by mriehl** [comment]
Praise the repo owner, for he is merciful :P

Thank you so much!
